---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 12459.
--- DateTime: 2025/5/29 19:47
---
--参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 数据key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId


-- 获取库存
local stock = redis.call('get', stockKey)
if not stock then
    return 1  -- 库存不存在，返回 1
end

stock = tonumber(stock)
if not stock or stock <= 0 then
    return 1  -- 非数字或库存不足，返回 1
end

-- 判断是否已下单
if redis.call('sismember', orderKey, userId) == 1 then
    return 2  -- 已下单，返回 2
end

-- 减库存 + 记录用户
redis.call('decr', stockKey)
redis.call('sadd', orderKey, userId)

return 0  -- 成功